# Problem 18
By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

3
7 4
2 4 6
8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

In [34]:
file = open('triangle2.txt', 'r')
triangle = file.read().split('\n')
file.close()
print(triangle)

['75', '95 64', '17 47 82', '18 35 87 10', '20 04 82 47 65', '19 01 23 75 03 34', '88 02 77 73 07 63 67', '99 65 04 28 06 16 70 92', '41 41 26 56 83 40 80 70 33', '41 48 72 33 47 32 37 16 94 29', '53 71 44 65 25 43 91 52 97 51 14', '70 11 33 28 77 73 17 78 39 68 17 57', '91 71 52 38 17 14 91 43 58 50 27 29 48', '63 66 04 68 89 53 67 30 73 16 69 87 40 31', '04 62 98 27 23 09 70 98 73 93 38 53 60 04 23']


In [35]:
import numpy as np

In [36]:
n = len(triangle[-1].split(' '))
matrix = np.zeros(shape=(n, n))
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [37]:
# Fill this matrix with triangle values
for i in range(0, len(triangle)):
    triangle[i] = triangle[i].split(' ')
print(triangle)

[['75'], ['95', '64'], ['17', '47', '82'], ['18', '35', '87', '10'], ['20', '04', '82', '47', '65'], ['19', '01', '23', '75', '03', '34'], ['88', '02', '77', '73', '07', '63', '67'], ['99', '65', '04', '28', '06', '16', '70', '92'], ['41', '41', '26', '56', '83', '40', '80', '70', '33'], ['41', '48', '72', '33', '47', '32', '37', '16', '94', '29'], ['53', '71', '44', '65', '25', '43', '91', '52', '97', '51', '14'], ['70', '11', '33', '28', '77', '73', '17', '78', '39', '68', '17', '57'], ['91', '71', '52', '38', '17', '14', '91', '43', '58', '50', '27', '29', '48'], ['63', '66', '04', '68', '89', '53', '67', '30', '73', '16', '69', '87', '40', '31'], ['04', '62', '98', '27', '23', '09', '70', '98', '73', '93', '38', '53', '60', '04', '23']]


In [38]:
for i, row in enumerate(triangle):
    matrix[i][0:len(row)] = triangle[i]
print(matrix)

[[75.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [95. 64.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [17. 47. 82.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [18. 35. 87. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [20.  4. 82. 47. 65.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [19.  1. 23. 75.  3. 34.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [88.  2. 77. 73.  7. 63. 67.  0.  0.  0.  0.  0.  0.  0.  0.]
 [99. 65.  4. 28.  6. 16. 70. 92.  0.  0.  0.  0.  0.  0.  0.]
 [41. 41. 26. 56. 83. 40. 80. 70. 33.  0.  0.  0.  0.  0.  0.]
 [41. 48. 72. 33. 47. 32. 37. 16. 94. 29.  0.  0.  0.  0.  0.]
 [53. 71. 44. 65. 25. 43. 91. 52. 97. 51. 14.  0.  0.  0.  0.]
 [70. 11. 33. 28. 77. 73. 17. 78. 39. 68. 17. 57.  0.  0.  0.]
 [91. 71. 52. 38. 17. 14. 91. 43. 58. 50. 27. 29. 48.  0.  0.]
 [63. 66.  4. 68. 89. 53. 67. 30. 73. 16. 69. 87. 40. 31.  0.]
 [ 4. 62. 98. 27. 23.  9. 70. 98. 73. 93. 38. 53. 60.  4. 23.]]


## Trying using Dynamic Programming
Adopting the max subchild at each path -> Does not work, may or may not work

In [12]:
longest_path = matrix[0, 0]
end = False
i, j = 0, 0
n = 4
while end != True:
    
    if i+1 >= n:
        end = True
        break
    
    # Code to keep adding the longest path
    if matrix[i+1, j] > matrix[i+1, j+1]:
        # Bottom element is greater
        longest_path += matrix[i+1, j]
        i, j = i+1, j
    
    elif matrix[i+1, j+1] > matrix[i+1, j]:
        # Right bottom element is greater
        longest_path += matrix[i+1, j+1]
        i, j = i+1, j+1

print(longest_path)

304.0


## Using Shortest Path Algorithm

In [9]:
import sys
import heapq

In [6]:
# Defining Classes to create a graph data structure
# Node class
class Node():
    
    # Constructor 
    def __init__(self, name):
        self.name = str(name)
        self.value = name
        self.adjacencyList = [] # adjanceny list of a node contains edges of the node
        self.predecessor = None
        self.minDistance = sys.maxsize
        self.visited = False
    
    # Comparator operator to compare nodes
    def __lt__(self, otherVertex):
        return self.minDistance < otherVertex.minDistance
    
    # Define __str__ method for Node 
    def __str__(self):
        return self.name

In [7]:
# Edge class
class Edge():
    
    # Constructor
    def __init__(self, startVertex, targetVertex, weight):
        self.startVertex = startVertex
        self.targetVertex = targetVertex
        # To find the longest path find the shorest path with negative weights
        self.weight = -weight

## Converting this number matrix into a node matrix

In [83]:
# Step 1 : Iterate over the matrix values which are not 0
node_matrix = np.ndarray.tolist(np.zeros(matrix.shape))
print(node_matrix)

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

In [84]:
for i in range(0, len(node_matrix)):
    for j in range(0, len(node_matrix[0])):
        if matrix[i, j] != 0:
            node_matrix[i][j] = Node(name=matrix[i, j])
print(node_matrix)

[[<__main__.Node object at 0x7f94b48edc88>, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [<__main__.Node object at 0x7f94b48ed828>, <__main__.Node object at 0x7f94b48ed908>, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [<__main__.Node object at 0x7f94b48edef0>, <__main__.Node object at 0x7f94b48ed7f0>, <__main__.Node object at 0x7f94b48edb00>, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [<__main__.Node object at 0x7f94b48ed898>, <__main__.Node object at 0x7f94b48edc50>, <__main__.Node object at 0x7f94b48edcc0>, <__main__.Node object at 0x7f94b48ed860>, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [<__main__.Node object at 0x7f94b48edba8>, <__main__.Node object at 0x7f94b48eddd8>, <__main__.Node object at 0x7f94b48edd30>, <__main__.Node object at 0x7f94b48edb70>, <__main__.Node object at 0x7f94b48ed940>, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [<__main__.Node object at 0x7f94b48edda0>, <__main__.Node o

In [85]:
# Poppulating the adjacnency Lists of the nodes
'''
Algo : 
1. For each node except the nodes in the last row (loop runs till row-1)
2. If Node is not 0
3. 3 cases ->
    1. if j==0 -> First column -> Only two subchilds (i+1,j), (i+1,j+1)
    2. else -> 3 subchilds (i+1,j-1), (i+1,j), (i+1,j+1)
'''
for i in range(0, len(node_matrix)-1):
    for j in range(0, len(node_matrix)):
        if node_matrix[i][j] != 0:
            
            if j==14:
                break
            
            if j==0: # Element belongs to the first column
                currentNode = node_matrix[i][j]
                # Referring to child nodes
                s1 = node_matrix[i+1][j]
                s2 = node_matrix[i+1][j+1]
                # Creating edges
                e1 = Edge(currentNode, s1, weight=currentNode.value + s1.value)
                e2 = Edge(currentNode, s2, weight=currentNode.value + s2.value)
                # Adding edges to adjacenylist of currentNode
                currentNode.adjacencyList.append(e1)
                currentNode.adjacencyList.append(e2)
            
            else: # Element belongs to middle or end column
                currentNode = node_matrix[i][j]
                # Referring to child nodes
                s1 = node_matrix[i+1][j]
                s2 = node_matrix[i+1][j+1]
                s3 = node_matrix[i+1][j-1]
                # Creating edges
                e1 = Edge(currentNode, s1, weight=currentNode.value + s1.value)
                e2 = Edge(currentNode, s2, weight=currentNode.value + s2.value)
                e3 = Edge(currentNode, s3, weight=currentNode.value + s3.value)
                # Adding edges to adjacenylist of currentNode
                currentNode.adjacencyList.append(e1)
                currentNode.adjacencyList.append(e2)
                currentNode.adjacencyList.append(e3)

In [72]:
# Djikstras algorithm for finding the longest(largest) path 
class Algorithm():
    
    def calculateShortestPath(self, startVertex):
        # Creating heap 
        q = []
        startVertex.minDistance = 0 # Set startdistance of initial vertex as 0
        heapq.heappush(q, startVertex)
        # While queue is not empty
        while q:
            
            actualVertex = heapq.heappop(q)
            for edge in actualVertex.adjacencyList:
                u = edge.startVertex
                v = edge.targetVertex
                newDistance = u.minDistance + edge.weight
                
                if newDistance < v.minDistance:
                    v.predecessor = u
                    v.minDistance = newDistance
                    heapq.heappush(q, v)
    
    def getShortestPathTo(self, targetVertex):
        
        currentVertex = targetVertex
        while currentVertex is not None:
            print(currentVertex.name)
            currentVertex = currentVertex.predecessor
    
    def getLongestPathSum(self, targetVertex):
        return targetVertex.minDistance

In [88]:
algo = Algorithm()
startVertex = node_matrix[0][0]
targetVertex = node_matrix[14][1]
print(startVertex.value, startVertex.adjacencyList)
print(targetVertex.value, startVertex.adjacencyList[0].targetVertex.value)

75.0 [<__main__.Edge object at 0x7f94b48522e8>, <__main__.Edge object at 0x7f94b4852358>]
62.0 95.0


In [91]:
algo.calculateShortestPath(startVertex)
algo.getShortestPathTo(targetVertex)
algo.getLongestPathSum(targetVertex)

62.0
66.0
91.0
70.0
71.0
72.0
41.0
65.0
77.0
75.0
82.0
87.0
82.0
64.0
75.0


-2023.0

## To get the maximum path sum, calculate path sums to all nodes in the bottom most row and pick the one with the maximum value


In [105]:
last_nodes = node_matrix[14]
distances = []
for node in last_nodes:
    algo = Algorithm()
    startVertex = node_matrix[0][0]
    targetVertex = node
    algo.calculateShortestPath(startVertex)
    distances.append((node.value, np.abs(algo.getLongestPathSum(targetVertex))))
print(distances)      

[(4.0, 1965.0), (62.0, 2023.0), (98.0, 2059.0), (27.0, 1930.0), (23.0, 1944.0), (9.0, 1958.0), (70.0, 2019.0), (98.0, 2047.0), (73.0, 1968.0), (93.0, 1988.0), (38.0, 1841.0), (53.0, 1856.0), (60.0, 1853.0), (4.0, 1513.0), (23.0, 1350.0)]
