# Problem 18
By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.

3
7 4
2 4 6
8 5 9 3

That is, 3 + 7 + 4 + 9 = 23.

Find the maximum total from top to bottom of the triangle below:

75
95 64
17 47 82
18 35 87 10
20 04 82 47 65
19 01 23 75 03 34
88 02 77 73 07 63 67
99 65 04 28 06 16 70 92
41 41 26 56 83 40 80 70 33
41 48 72 33 47 32 37 16 94 29
53 71 44 65 25 43 91 52 97 51 14
70 11 33 28 77 73 17 78 39 68 17 57
91 71 52 38 17 14 91 43 58 50 27 29 48
63 66 04 68 89 53 67 30 73 16 69 87 40 31
04 62 98 27 23 09 70 98 73 93 38 53 60 04 23

In [40]:
file = open('triangle2.txt', 'r')
triangle = file.read().split('\n')
file.close()
print(triangle)

['75', '95 64', '17 47 82', '18 35 87 10', '20 04 82 47 65', '19 01 23 75 03 34', '88 02 77 73 07 63 67', '99 65 04 28 06 16 70 92', '41 41 26 56 83 40 80 70 33', '41 48 72 33 47 32 37 16 94 29', '53 71 44 65 25 43 91 52 97 51 14', '70 11 33 28 77 73 17 78 39 68 17 57', '91 71 52 38 17 14 91 43 58 50 27 29 48', '63 66 04 68 89 53 67 30 73 16 69 87 40 31', '04 62 98 27 23 09 70 98 73 93 38 53 60 04 23']


In [41]:
import numpy as np

In [42]:
n = len(triangle[-1].split(' '))
matrix = np.zeros(shape=(n, n))
print(matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [43]:
# Fill this matrix with triangle values
for i in range(0, len(triangle)):
    triangle[i] = triangle[i].split(' ')
print(triangle)

[['75'], ['95', '64'], ['17', '47', '82'], ['18', '35', '87', '10'], ['20', '04', '82', '47', '65'], ['19', '01', '23', '75', '03', '34'], ['88', '02', '77', '73', '07', '63', '67'], ['99', '65', '04', '28', '06', '16', '70', '92'], ['41', '41', '26', '56', '83', '40', '80', '70', '33'], ['41', '48', '72', '33', '47', '32', '37', '16', '94', '29'], ['53', '71', '44', '65', '25', '43', '91', '52', '97', '51', '14'], ['70', '11', '33', '28', '77', '73', '17', '78', '39', '68', '17', '57'], ['91', '71', '52', '38', '17', '14', '91', '43', '58', '50', '27', '29', '48'], ['63', '66', '04', '68', '89', '53', '67', '30', '73', '16', '69', '87', '40', '31'], ['04', '62', '98', '27', '23', '09', '70', '98', '73', '93', '38', '53', '60', '04', '23']]


In [44]:
for i, row in enumerate(triangle):
    matrix[i][0:len(row)] = triangle[i]
print(matrix)

[[75.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [95. 64.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [17. 47. 82.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [18. 35. 87. 10.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [20.  4. 82. 47. 65.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [19.  1. 23. 75.  3. 34.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [88.  2. 77. 73.  7. 63. 67.  0.  0.  0.  0.  0.  0.  0.  0.]
 [99. 65.  4. 28.  6. 16. 70. 92.  0.  0.  0.  0.  0.  0.  0.]
 [41. 41. 26. 56. 83. 40. 80. 70. 33.  0.  0.  0.  0.  0.  0.]
 [41. 48. 72. 33. 47. 32. 37. 16. 94. 29.  0.  0.  0.  0.  0.]
 [53. 71. 44. 65. 25. 43. 91. 52. 97. 51. 14.  0.  0.  0.  0.]
 [70. 11. 33. 28. 77. 73. 17. 78. 39. 68. 17. 57.  0.  0.  0.]
 [91. 71. 52. 38. 17. 14. 91. 43. 58. 50. 27. 29. 48.  0.  0.]
 [63. 66.  4. 68. 89. 53. 67. 30. 73. 16. 69. 87. 40. 31.  0.]
 [ 4. 62. 98. 27. 23.  9. 70. 98. 73. 93. 38. 53. 60.  4. 23.]]


In [45]:
longest_path = matrix[0, 0]
end = False
i, j = 0, 0
n = 4
while end != True:
    
    if i+1 >= n:
        end = True
        break
    
    # Code to keep adding the longest path
    if matrix[i+1, j] > matrix[i+1, j+1]:
        # Bottom element is greater
        longest_path += matrix[i+1, j]
        i, j = i+1, j
    
    elif matrix[i+1, j+1] > matrix[i+1, j]:
        # Right bottom element is greater
        longest_path += matrix[i+1, j+1]
        i, j = i+1, j+1

print(longest_path)

304.0
